//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int MessageID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual ChatSession ChatSession { get; set; }
    }
}
