//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductID { get; set; }
        public int SpecificationID { get; set; }
        public string SpecificationValue { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductSpecification ProductSpecification { get; set; }
    }
}
